# Form implementation generated from reading ui file 'popup_pembayarann.ui'
#
# Created by: PyQt6 UI code generator 6.10.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Pembayaran(object):
    def setupUi(self, Pembayaran):
        Pembayaran.setObjectName("Pembayaran")
        Pembayaran.resize(565, 428)
        self.labelTitle = QtWidgets.QLabel(parent=Pembayaran)
        self.labelTitle.setGeometry(QtCore.QRect(40, 10, 481, 81))
        self.labelTitle.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("background-color: rgb(191, 191, 142);")
        self.labelTitle.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.labelTitle.setObjectName("labelTitle")
        self.btnKembali = QtWidgets.QPushButton(parent=Pembayaran)
        self.btnKembali.setGeometry(QtCore.QRect(460, 370, 75, 24))
        self.btnKembali.setStyleSheet("background-color: rgb(202, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnKembali.setObjectName("btnKembali")
        self.label = QtWidgets.QLabel(parent=Pembayaran)
        self.label.setGeometry(QtCore.QRect(-2, -5, 571, 431))
        self.label.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.textBrowser = QtWidgets.QTextBrowser(parent=Pembayaran)
        self.textBrowser.setGeometry(QtCore.QRect(40, 120, 481, 191))
        self.textBrowser.setStyleSheet("background-color: rgb(220, 220, 164);")
        self.textBrowser.setObjectName("textBrowser")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=Pembayaran)
        self.lineEdit_2.setGeometry(QtCore.QRect(50, 200, 461, 22))
        self.lineEdit_2.setStyleSheet("color: rgb(85, 0, 255);")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=Pembayaran)
        self.lineEdit_3.setGeometry(QtCore.QRect(50, 240, 461, 22))
        self.lineEdit_3.setStyleSheet("color: rgb(255, 85, 0);")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=Pembayaran)
        self.lineEdit_4.setGeometry(QtCore.QRect(50, 280, 461, 22))
        self.lineEdit_4.setStyleSheet("color: rgb(0, 131, 197);")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=Pembayaran)
        self.lineEdit_5.setGeometry(QtCore.QRect(50, 160, 461, 22))
        self.lineEdit_5.setStyleSheet("\n"
"color: rgb(0, 170, 255);")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label.raise_()
        self.labelTitle.raise_()
        self.btnKembali.raise_()
        self.textBrowser.raise_()
        self.lineEdit_2.raise_()
        self.lineEdit_3.raise_()
        self.lineEdit_4.raise_()
        self.lineEdit_5.raise_()

        self.retranslateUi(Pembayaran)
        QtCore.QMetaObject.connectSlotsByName(Pembayaran)

    def retranslateUi(self, Pembayaran):
        _translate = QtCore.QCoreApplication.translate
        Pembayaran.setWindowTitle(_translate("Pembayaran", "Metode Pembayaran"))
        self.labelTitle.setText(_translate("Pembayaran", "Pilih Metode Pembayaran"))
        self.btnKembali.setText(_translate("Pembayaran", "Kembali"))
        self.textBrowser.setHtml(_translate("Pembayaran", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><meta charset=\"utf-8\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"hr { height: 1px; border-width: 0; }\n"
"li.unchecked::marker { content: \"\\2610\"; }\n"
"li.checked::marker { content: \"\\2612\"; }\n"
"</style></head><body style=\" font-family:\'Segoe UI\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Pilih Metode Pembayaran</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.lineEdit_2.setText(_translate("Pembayaran", " BTN                                                 VA: 90012345678                Charge : Rp.2.500"))
        self.lineEdit_3.setText(_translate("Pembayaran", " Mandiri                                           VA: 89312345678                Charge : Rp.4000"))
        self.lineEdit_4.setText(_translate("Pembayaran", " BCA                                                  VA: 39011234567                Charge : Rp.6.500"))
        self.lineEdit_5.setText(_translate("Pembayaran", "DANA                                             VA:  39010824567                Charge : Rp 4.500"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Pembayaran = QtWidgets.QWidget()
    ui = Ui_Pembayaran()
    ui.setupUi(Pembayaran)
    Pembayaran.show()
    sys.exit(app.exec())
